### ISSUE TITLE
Update charge voltage

### ISSUE THREAD

**Issue by morgant** [splorp/newton-faq#1]
Line 1077 of newton-faq-hardware.html says "5V DC, 400mA", but [this thread on the 68kMLA forums](https://68kmla.org/forums/viewtopic.php?f=14&t=23453#p232040) mentions is should be **7.5V**, not 5V. I haven't verified this info.

**Comment by cryoplants** [comment]
My official power supply for the MP100, dated 1993, for the US/Canada (Apple power supply model H1300) states "7.0 V 0.5 A"

I also have a British power supply dated 1993, so I assume it's also for the MP100/OMP, Apple power supply model H2200, states "7.0 V 0.5 A".

**Comment by splorp** [comment]
Thanks for this information, @cryoplants … I think I’ll tackle updating this portion of the FAQ next.

And I haven’t forgotten about you either, @morgant.

**Comment by splorp** [comment]
These details and fixes have been included in commit 60e172a8a0e783da7e31cdef80ee4e20fe601990

I rewrote, clarified, and expanded most of the question.

http://newtonfaq.com/newton-faq-hardware.html#IIB7
