### ISSUE TITLE
How to remove or bypass the PIN code

### ISSUE THREAD

**Issue by splorp** [splorp/newton-faq#11]
There are multiple ways to remove or bypass the PIN code (or password) that has been set on a Newton device.

**Hard Reset**

If you do not want to save any of the data or applications on the Newton, then the PIN can be reset by performing a Hard Reset (or “Brain Wipe”). This method basically resets the Newton to factory settings.

**Battering Ram Pro**

If you want to save the data on the Newton, then you’ll need to run an application called Battering Ram Pro. This package needs to be installed on a PCMCIA card, inserted into the Newton, and activated from there. It uses a brute force method to crack the PIN code.

http://myapplenewton.blogspot.com/2009/11/lost-your-power-on-password-battering.html
http://www.unna.org/unnasearch/entry.php?pkey=339

**NewtonUnlock**

Another small program called NewtonUnlock also works this way. Refer to the [README.TXT](https://github.com/splorp/newton-faq/files/6097731/README.TXT) document.

http://myapplenewton.blogspot.com/2011/03/lost-your-power-on-password-there-is.html
https://web.archive.org/web/20001007032009/http://download.planetnewton.com/download/util/newtonunlock-2.1.zip

**Comment by splorp** [comment]
Closed per commit c001144

**Comment by real-fink** [comment]
should probably specify that this doesn't work on NOS2.1 devices...

**Comment by splorp** [comment]
Thanks for the reminder.

I know that NOS 2.1 is an issue.

I need to do some additional testing to confirm whether it works on NOS 2.0 or not.
