### ISSUE TITLE
Community resources, groups, blogs, discussions, &c.

### ISSUE THREAD

**Issue by splorp** [splorp/newton-faq#16]
AppleNewton Slack
https://applenewton.slack.com/

NewtonScript Slack
https://newtonscript-lang.slack.com/

#newtonscript IRC Channel
https://newtonscript-lang.slack.com/archives/C7YFUBPRA/p1622135585000100

Marisa Giancarla’s Newton City portal for the Newton
https://newtoncity.org/

BBS for the Apple Newton
https://bbs.newtoncity.org/

Newton Discord
https://discord.gg/PVEAJAQZMH

Apple Newton Users Group
https://www.facebook.com/groups/1718579898362694

Are there others?

**Comment by SylvainPilet** [comment]
Grant,

Oh yes!
There is also the group that we have created that is starting to grow:
https://www.facebook.com/groups/Apple.Newton.MessagePad.News


Sylvain Pilet

**Comment by splorp** [comment]
Thanks, Sylvain!

**Comment by splorp** [comment]
This issue has been address per commit 1a71e57
