### ISSUE TITLE
Year 2010 problem and solution

### ISSUE THREAD

**Issue by splorp** [splorp/newton-faq#17]
Holy Toledo!

We need to add Eckhart’s Y2010 information to the [Are there known bugs in the Newton OS?](http://newtonfaq.com/newton-faq-nos.html#IIIC2) section.

https://40hz.org/Pages/newton/hacking/newton-year-2010-problem/

- Patch 711000: for the MessagePad 2000/2100 US
- Patch 73J186: for the eMate 300
- Patch 74J185: for the MessagePad 2100 German

Also incorporate Avi’s [Fix2010](http://www.drissman.com/avi/newton/Fix2010/) information from the [Is the Newton Y2K compliant?](http://newtonfaq.com/newton-faq-nos.html#IIIC1) question and cross-reference.

**Comment by SylvainPilet** [comment]
It would be nice to make this section much more readable and understandable. 
That there is a link to the "Newton OS: Year 2000 (Y2K) Compliance" is one thing, but it doesn't help to understand what is going on with each Newton today.

It would be nice to do something like this:
- for each Newton is there a problem with the dates, 
- if yes, from which date
- - if yes, is there a solution
- - - list of solutions, are the solutions permanent
- - - - if the solution is not perennial when the problem will come back…


Sorry I didn't write this down, it's just a proposal on the fly…
 


> Le 12 avr. 2021 à 20:31, Grant Hutchinson ***@***.***> a écrit :
> 
> 
> Holy Toledo!
> 
> We need to add Eckhart’s Y2010 information to the Are there known bugs in the Newton OS? section.
> 
> https://40hz.org/Pages/newton/hacking/newton-year-2010-problem/
> 
> 	• Patch 711000: for the MessagePad 2000/2100 US
> 	• Patch 73J186: for the eMate 300
> 	• Patch 74J185: for the MessagePad 2100 German
> Also incorporate Avi’s Fix2010 information from the Is the Newton Y2K compliant? question and cross-reference.
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.
> 

Sylvain Pilet

http://message-pad.net
http://messagepad.no-ip.org:3680 [NPDS Tracker]

**Comment by splorp** [comment]
My plan was to add a new question to the “bugs” section that specifically addresses the Year 2010 problem. It would be separate from the Y2K question and different than the “What is the Dates/Find bug?” issue.

Avi’s fix would be included in the new question, along with Eckhart’s information and how the issue affects various devices.

The main reason why the Year 2010 information hadn’t been added to the FAQ is because the last major FAQ update (besides the recent updates I have been working on) occurred in 2003 … seven years before Y2010!

**Comment by splorp** [comment]
This issue has been resolved per commit eda86b1
