### ISSUE TITLE
Updating the FAQ?

### ISSUE THREAD

**Issue by newtonhonk** [splorp/newton-faq#7]
Hi, this list so great. I just have a question: A lot of links are dead. Is this list just for archiving or can it be updated. For an example add recent software like NCX, Einstein, Leibnitz an NewTen?

**Comment by splorp** [comment]
Yes, the whole point of publishing the Newton FAQ on GitHub was to get other people involved in the updating process. Go ahead a fork the repo, and submit any changes as pull requests.

I am trying to go through and replace dead links with version from the Internet Archive, but it’s a slow process.

**Comment by nasendackel** [comment]
Ok, that's great!

**Comment by splorp** [comment]
A couple of updates.

Added NCX: 92a74f0
Added NewTen: 32d4d1c
